# Generated by Django 4.2.24 on 2025-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=32, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=32, verbose_name="用户名"),
        ),
    ]
