# Generated by Django 4.2.24 on 2025-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12, verbose_name="性别")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("email", models.EmailField(max_length=32, verbose_name="邮箱")),
            ],
        ),
    ]
