# Generated by Django 4.2.24 on 2025-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=12, verbose_name="部门名称")),
                ("count", models.IntegerField(verbose_name="人数")),
            ],
        ),
    ]
